//
// HealthcheckData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HealthcheckData: Codable, JSONEncodable, Hashable {

    public var uptime: String?
    public var version: String?
    public var requests: Int?

    public init(uptime: String? = nil, version: String? = nil, requests: Int? = nil) {
        self.uptime = uptime
        self.version = version
        self.requests = requests
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uptime
        case version
        case requests
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(uptime, forKey: .uptime)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(requests, forKey: .requests)
    }
}

