//
// OptionEndpoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OptionEndpoint: Codable, JSONEncodable, Hashable {

    public var lang: [OptionsObject]?

    public init(lang: [OptionsObject]? = nil) {
        self.lang = lang
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lang
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lang, forKey: .lang)
    }
}

